apiVersion: funceasy.com/v1
kind: Function
metadata:
  name: 187c7554ec3c4bad8b0b1914a5dee99e
  namespace: funceasy
  labels:
    app: funceasy_function
    function: funcName.ns.user
spec:
  # Add fields here
  size: 1
  function: |
    const _ = require('lodash');
    module.exports = {
      foo: function (event, context) {
        return 123
      },
      bar: function (event, context) {
        let res = {origin: "origin"};
        _.assign(res, {date: new Date().toTimeString()});
        return res;
      },
      test: function (event, context) {
        return "test"
      }
    }
  identifier: funcName.ns.user
  version: 0.0.2
  handler: test.foo
  runtime: nodeJS:10
  timeout: "1000"
  deps: |
    {
      "name": "example",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "directories": {
        "test": "test"
      },
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "lodash": "^4.17.15"
      }
    }
  contentType: text
  dataServiceToken: aaabbbCCC
  dataSource: test-database
  externalService:
    test-alias: 192.168.0.0:8999
  HPAPrediction: true
  cpuTargetAverageUtilization: 10
