apiVersion: apps/v1
kind: Deployment
metadata:
  name: function-operator
  namespace: funceasy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: function-operator
  template:
    metadata:
      labels:
        name: function-operator
    spec:
      serviceAccountName: function-operator
      containers:
        - name: function-operator
          # Replace this with the built image name
          image: ziqiancheng/function-operator:v1.0.0
          command:
          - function-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "function-operator"
