kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: function-operator
  namespace: funceasy
subjects:
- kind: ServiceAccount
  name: function-operator
roleRef:
  kind: Role
  name: function-operator
  apiGroup: rbac.authorization.k8s.io
